# Generated by Django 5.0.7 on 2024-12-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=11, max_length=30),
            preserve_default=False,
        ),
    ]
