# Generated by Django 5.0.7 on 2024-12-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_image_tag_created_on_tag_name_tag_icon_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='icon',
        ),
        migrations.AddField(
            model_name='item',
            name='etsy_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
