# Generated by Django 5.0.7 on 2024-12-18 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_tag_icon_item_etsy_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-created_on']},
        ),
    ]
