# Generated by Django 5.0.7 on 2025-01-13 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='description',
        ),
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
