# Generated by Django 5.0.7 on 2025-01-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_image_description_remove_image_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('INSTAGRAM', 'INSTAGRAM'), ('ETSY', 'ETSY'), ('FACEBOOK', 'FACEBOOK')], max_length=50)),
                ('link', models.URLField()),
            ],
        ),
    ]
